version: '3'

services:
    spark:
        build: .
        container_name: spark
        expose:
            - 4040
        ports:
            - 4040:4040
        environment:
            SPARK_PUBLIC_DNS: spark
        networks:
            - lampda-network

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        container_name: zookeeper
        networks:
            - lampda-network

    kafka:
        image: wurstmeister/kafka:0.10.0.0
        container_name: kafka
        ports:
            - "9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "Topic1:1:1,Topic2:1:1"
        networks:
            - lampda-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        container_name: elasticsearch
        environment:
            - "cluster.initial_master_nodes=elasticsearch"
            - "node.name=elasticsearch"
        networks:
            - lampda-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.1.1
        container_name: kibana
        environment:
            - "elasticsearch.url=http://elasticsearch:9200 "
        networks:
            - lampda-network
        depends_on:
            - elasticsearch
        ports:
          - "5601:5601"

networks:
    lampda-network:
        driver: bridge